<?php

return [
    'Anodoncia',
    'Dientes supernumerarios',
    'Anomalías del tamaño y de la forma del diente',
    'Dientes moteados',
    'Alteraciones en la formación dentaria',
    'Alteraciones hereditarias de la estructura dentaria, no clasificadas en otra parte',
    'Alteraciones en la erupción dentaria',
    'Síndrome de la erupción dentaria',
    'Otros trastornos del desarrollo de los dientes',
    'Trastorno del desarrollo de los dientes, no especificado',
    'Dientes incluidos',
    'Dientes impactados',
    'Caries limitada al esmalte',
    'Caries de la dentina',
    'Caries del cemento',
    'Caries dentaria detenida',
    'Odontoclasia',
    'Otras caries dentales',
    'Caries dental, no especificada',
    'Atrición excesiva de los dientes',
    'Abrasión de los dientes',
    'Erosión de los dientes',
    'Reabsorción patológica de los dientes',
    'Hipercementosis',
    'Anquilosis dental',
    'Depósitos [acreciones] en los dientes',
    'Cambios posteruptivos del color de los tejidos dentales duros',
    'Otras enfermedades especificadas de los tejidos duros de los dientes',
    'Enfermedad no especificada de los tejidos dentales duros',
    'Pulpitis',
    'Necrosis de la pulpa',
    'Degeneración de la pulpa',
    'Formación anormal de tejido duro en la pulpa',
    'Periodontitis apical aguda originada en la pulpa',
    'Periodontitis apical crónica',
    'Absceso periapical con fistula',
    'Absceso periapical sin fistula',
    'Quiste radicular',
    'Otras enfermedades y las no especificadas de la pulpa y del tejido periapical',
    'Gingivitis aguda',
    'Gingivitis crónica',
    'Periodontitis aguda',
    'Periodontitis crónica',
    'Periodontosis',
    'Otras enfermedades periodontales',
    'Enfermedad de periodonto, no especificada',
    'Retracción gingival',
    'Hiperplasia gingival',
    'Lesiones de la encía y de la zona edéntula asociadas con traumatismo',
    'Otros trastornos especificados de la encía y de la zona edéntula',
    'Trastorno no especificado de la encía y de la zona edéntula',
    'Anomalias evidentes del tamaño de los maxilares',
    'Anomalias de la relación maxilobasilar',
    'Anomalias de la relación entre los arcos dentarios',
    'Anomalias de la posición del diente',
    'Maloclusión de tipo no especificado',
    'Anomalias dentofaciales funcionales',
    'Trastornos de la articulación temporomaxilar',
    'Otras anomalías dentofaciales',
    'Anomalía dentofacial, no especificada',
    'Exfoliación de los dientes debida a causas sistémicas',
    'Perdida de dientes debida a accidente, extracción o enfermedad periodontal local',
    'Atrofia de reborde alveolar desdentado',
    'Raíz dental retenida',
    'Otras afecciones especificadas de los dientes y de sus estructuras de sostén',
    'Trastorno de los dientes y de sus estructuras de sostén, no especificado',
    'Quistes originados por el desarrollo de los dientes',
    'Quistes de las fisuras (no odontogénicos)',
    'Otros quistes de los maxilares',
    'Otros quistes de la región bucal, no clasificados en otra parte',
    'Quiste de la región bucal, sin otra especificación',
    'Trastornos del desarrollo de los maxilares',
    'Granuloma central de células gigantes',
    'Afecciones inflamatorias de los maxilares',
    'Alveolitis del maxilar',
    'Otras enfermedades especificadas de los maxilares',
    'Enfermedad de los maxilares, no especificada',
    'Atrofia de glándula salival',
    'Hipertrofia de glándula salival',
    'Sialadenitis',
    'Absceso de glándula salival',
    'Fistula de glándula salival',
    'Sialolitiasis',
    'Mucocele de glándula salival',
    'Alteraciones de la secreción salival',
    'Otras enfermedades de las glándulas salivales',
    'Enfermedad de glándula salival. No especificada',
    'Estomatitis aftosa recurrente',
    'Otras formas de estomatitis',
    'Celulitis y absceso de boca',
    'Enfermedades de los labios',
    'Mordedura del labio y de la mejilla',
    'Leucoplasia y otras alteraciones del epitelio bucal, incluyendo la lengua',
    'Leucoplasia pilosa',
    'Granuloma y lesiones semejantes de la mucosa bucal',
    'Fibrosis de la submucosa bucal',
    'Hiperplasia irritativa de la mucosa bucal',
    'Otras lesiones y las no especificadas de la mucosa bucal',
    'Glositis',
    'Lengua geográfica',
    'Glositis romboidea mediana',
    'Hipertrofia de las papilas linguales',
    'Atrofia de las papilas linguales',
    'Lengua plegada',
    'Glosodinia',
    'Otras enfermedades de la lengua',
    'Enfermedad de la lengua, no especificada',
    'Fisura del paladar duro, bilateral',
    'Fisura del paladar duro, unilateral',
    'Fisura del paladar blando, bilateral',
    'Fisura del paladar blando, unilateral',
    'Fisura del paladar duro y del paladar blando, bilateral',
    'Tumor maligno del Labio',
    'Neoplasias malignas de la base de la lengua',
    'Neoplasias malignas de otras partes y sin especificar de la lengua',
    'Neoplasias malignas de la encía',
    'Neoplasias malignas de la base de la boca',
    'Neoplasias malignas del paladar',
    'Neoplasias malignas de la glándula parótida',
    'Neoplasias malignas de otras partes y sin especificar de las glándulas salivares',
];
